### ISSUE TITLE
Grumbles the Lame Wizard port

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/bot#2]
Could be an idea to have Hyperbot be a game-master for [Grumbles the Lame Wizard](https://github.com/hyperoslo/grumbles).
- Use [Slack's API](https://api.slack.com/) to manage rooms such as `#castle`, `#bar`.
- Use Hubot's brain to store game state for each user or perhaps even create a multiplayer version!
- Users can type commands such as `look at`, `move to`, `combine` which will be picked up by Hyperbot and executed accordingly.
- Moving between locations would involve Hyperbot kicking and inviting users from rooms on Slack.
- Slack seems to allow changing name and icon on a per-message basis, which could be fantastic for impersonating characters such as the princess, a troll etc.

**Comment by sindrenm** [comment]
Oh, that is such an awesome game! Would love to meet the people behind it. :smiley:

**Comment by timkurvers** [comment]
:heart:
